---

- hosts: azure
  tasks:
      - name: "update cache"
        apt: update_cache=yes upgrade=dist
        sudo: true

      - name: Install Basic Packages required on all machines
        sudo: yes
        apt:
            pkg: '{{ item }}'
            state: present
        with_items:
            - nano
            - tmux
            - git
            

