---
- hosts: all
  tasks:
    - name: elastic
      apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present validate_certs=False
      sudo: yes
    - name: elastic key
      apt_repository: repo='deb http://packages.elastic.co/logstashforwarder/debian stable main' state=present update_cache=yes
      sudo: yes
    - name: add logstashforwarder
      apt: name='logstash-forwarder' state=present update_cache=yes
      sudo: yes
    - name: add config
      template: src=/home/zoey/logstash-forwarder.conf dest=/etc/logstash-forwarder.conf
      sudo: yes
   - name: create folder
      file: path='/etc/pki/tls/certs/' state=directory recurse=yes
      sudo: yes
   - name: add key
     template: src=/home/zoey/logstash-forwarder.crt dest=/etc/pki/tls/certs/logstash-forwader.crt
     sudo: yes
   - name: start logstash
    service: name=logstash-forwarder state=started enabled=yes
    sudo: yes
  - name: stop puppet
    service: name=puppet state=stopped enabled=no
    sudo: yes
    ignore_errors: True
  - name: copy puppet uninstall
    copy: src=/home/zoey/puppet-enterprise-uninstaller dest=/home/zoey/puppet-enterprise-uninstaller mode=777
  - name: copy puppet utilties
    copy: src=/home/zoey/utilities dest=/home/zoey/utilities
  - name: run uninstaller
    command: ./puppet-enterprise-uninstaller -d -p -y
    sudo: yes
    register: uninstall
  - name: "reboot after puppet uninstall"
    command: /sbin/shutdown -r now
    when: uninstall|changed
    sudo: yes
