---
- hosts: haproxy
  tasks:
    - name: Install HAProxy
      apt: pkg=haproxy state=present
      sudo: yes

    - name: Copy config
      copy: src=../config/haproxy.cfg dest=/etc/haproxy/haproxy.cfg
      sudo: yes

    - name: restart haproxy
      service: name=haproxy state=restarted
      sudo: yes
