---
- hosts: localhost
  connection: local 
  tasks:
    - local_action:
       module: azure
       name: Cassandra1
       role_size: Small
       image: b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20150123-en-us-30GB
       location: 'Central US'
       user: zoey
       ssh_cert_path: /home/zoey/key.pem
       storage_account: Projectz
       wait: yes
       password: $password
