---
- hosts: cassandra
  tasks:

  - name: Cassandra Deb key
    apt_repository: repo='deb http://www.apache.org/dist/cassandra/debian 30x main' state=present update_cache=yes
    sudo: yes

  - name: Cassandra Deb-src key
    apt_repository: repo='deb-src http://www.apache.org/dist/cassandra/debian 30x main' state=present update_cache=yes
    sudo: yes

  - name: Add key 1
    apt_key: id=F758CE318D77295D keyserver=hkp://pgp.mit.edu
    sudo: yes

  - name: add key 2
    apt_key: id=2B5C1B00 keyserver=hkp://pgp.mit.edu
    sudo: yes

  - name: add key 3
    apt_key: id=0353B12C keyserver=hkp://pgp.mit.edu
    sudo: yes

  - name: add jdk
    apt_repository: repo='ppa:openjdk-r/ppa'
    sudo: yes

  - name: update cache
    apt: update_cache=yes
    sudo: yes

  - name: install jdk
    apt: name=openjdk-8-jdk state=present
    sudo: yes

  - name: install cassandra
    apt: name=cassandra state=present
    sudo: yes

  - name: copy Cassandra config
    copy: src=/home/zoey/cassandra.yaml dest=/etc/cassandra/cassandra.yaml
    sudo: yes

  - name: restart Cassandra
    service: name=cassandra state=restarted
    sudo: yes
